stages:
  - build
  - test
  - deploy

default:
  image: oven/bun:latest

build-job:
  stage: build
  script:
    - bun i
  artifacts:
    paths:
      - node_modules/

automated-test-job:
  stage: test
  script:
    - bun test

manual-test-job:
  stage: test
  script:
    - echo "Wait QA to Review"
  when: manual
  allow_failure: false

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application.."
    - echo "Application successfully deployed."
